### ISSUE TITLE
How to retrieve breakpoints?

### ISSUE THREAD

**Issue by rexdouglass** [ryantibs/genlasso#1]
First, thanks for a fantastic package.

I've read the documentation and vignette, and I can't figure out how to retrieve the location of the knots themselves. I've looked at each of the returned objects from trendfilter and got as far as picking apart the returned pathobjs object, but I'm stuck.

Thanks for any help you can provide.

**Comment by ryantibs** [comment]
Glad you like the package.  You want the `lambda` component of the returned path object.  It is a vector containing the knots.
