### ISSUE TITLE
Outdated citation information

### ISSUE THREAD

**Issue by ararslan** [ryantibs/genlasso#2]
One of the references is Arnold and Tibshirani's _Efficient Implementations of the Generalized Lasso Dual Path Algorithm_, but it lists this as being a preprint on arXiv. It's since been published in the Journal of Computational and Graphical Statistics, so I imagine that the citation information should be updated to reflect this. The full information in BibTeX form is:

``` latex
@article{efficientdualpath
  title = {Efficient Implementations of the Generalized Lasso Dual Path Algorithm},
  author = {Arnold, Taylor and Tibshirani, Ryan},
  journal = {Journal of Computational and Graphical Statistics},
  volume = 25,
  number = 1,
  year = 2016,
  month = 3,
  pages = {1-27},
  doi = {10.1080/10618600.2015.1008638}
}
```

That article is how I found this package. 😄

**Comment by ryantibs** [comment]
Thanks, I updated it.
