### ISSUE TITLE
The document of softthresh function might be mistake

### ISSUE THREAD

**Issue by teramonagi** [ryantibs/genlasso#3]
There is the statement

```
given the solution path corresponding to \eqn{\gamma=0}.
```

in https://github.com/statsmaths/genlasso/blob/master/man/softthresh.Rd.

But, it seems to be a mistake because we can set any gamma parameter to this function.
Is it correct?

**Comment by ryantibs** [comment]
Not a mistake, the documentation is describing what the *input* to this function is.  It's the solution path with gamma = 0.  The *output* is the soft-thresholded path, where you can set any gamma you want.
